server:
  port: 8089

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
spring:
  cloud:
    gateway:
      routes:
        - id: agency_service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/agencies/**
        - id: service_service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/service/**
